import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const InterFont = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600" ,"700", "800", "900"],
});

export const metadata = {
  title: "More Rings",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${InterFont.variable} antialiased`}
      >
        <Header />
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
